services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: hessprotector-backend:latest
    container_name: hess_backend_prod
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
      # - GEMINI_API_KEY=${GEMINI_API_KEY}
      # - SECRET_KEY=${SECRET_KEY}
      - SQLITE_DB_PATH=/app/data/hess_protector.db
    volumes:
      - hess_data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: hess-frontend:latest
    container_name: hess_frontend_prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  hess_data:
